### ISSUE TITLE
Disable Shortcut in some app.

### ISSUE THREAD

**Issue by tshu-w** [dexterleng/vimac#139]
I want to bind vimac shortcut to more general key, however, it may conflict with some app shortcut.(e.g. iterm2, emacs). It would be much appreciated if vimac supports disable in some app.

**Comment by jornetsimon** [comment]
Agreed, this is a must feature.

**Comment by dsernst** [comment]
Related to https://github.com/dexterleng/vimac/issues/145

**Comment by dexterleng** [comment]
I'm hesitant in adding this feature because:

1. Additional thing for me to maintain
2. Might bloat the preferences panel
3. Seems very niche, I don't know any menu bar apps that have this shortcut blacklist option. Please enlighten me with some examples.

**Comment by dexterleng** [comment]
Maybe I'm wrong here, but perhaps users of this application are using shortcuts that convenient to reach since they need to click stuff quite frequently, and those convenient shortcuts are also registered by applications.

If the above hypothesis is true, then the root issue is that the current mechanism (shortcuts) to activate Vimac is not ideal, and I should explore other mechanisms that do not have such issue.

**Comment by dexterleng** [comment]
An alternative mechanism I've explored is key-sequence based activation (e.g. "fd" to activate Hint-mode). This solves the shortcut conflict issue and should be even more convenient than shortcuts. Try it out and do let me know what you think!

<img width="615" alt="Screenshot 2021-03-04 at 9 29 17 PM" src="https://user-images.githubusercontent.com/34204380/109970988-ada36180-7d30-11eb-833b-ba2752bae4c3.png">

**Comment by tshu-w** [comment]
@dsernst I have tried the key sequence and for me it is often easy to hit it by mistake as I often press jk quickly. So I think the current solution is to choose a shortcut without conflicts

**Comment by dexterleng** [comment]
@tshu-w May I ask what shortcuts/special bindings are you using? Do you find it inconvenient to repeatedly hit the shortcut?

**Comment by tshu-w** [comment]
@dexterleng I'm using cmd-option-control(space-h) h/j, It is a bit inconvenient indeed. 
The reason I gave up on key sequences before was that I emulated the Spacemacs shortcut in Emacs, using space f-s to save the file, and also moving up and down the line by j k, or typing Chinese by double spelling (jk for jing, like 京) so I often triggered vimac by mistake. turning down Reset Delay (seconds) doesn't work, so I have to change some uncommon key sequence.

I think the best way is to disable vimac in some applications, and since we can do it with other shortcut applications like Karabiner, shkd or hammperspoon, I'll close this issue for now. thanks for your attention!

Translated with www.DeepL.com/Translator (free version)

**Comment by PegasusWang** [comment]
DIsable vimac in iterm2 will be convenient

**Comment by tomoakley** [comment]
I use Alacritty and vim to write code. I tried the sequence key activation of `jk` for scroll mode which is great but makes vim/alacritty lag slightly when I hit `j`, I assume because it's waiting for the next key via the reset delay time. It'd be useful to disable vimac in Alacritty as it has absolutely no use there (no scroll via normal methods, no mouse targets - at least for me)
