### ISSUE TITLE
The hints overlapped with button 

### ISSUE THREAD

**Issue by albert-ying** [dexterleng/vimac#181]
Hi, thank you for this great tool. I'm a Vimium user for a long time and really like your work.

If you check the Vimium, you will see they are not overlapped with the button, but at top left side of the button. Thus, I can visual the button and see what they are while the hints are activated. However, for Vimac, the hint is at the center of the button, and it makes the button unreadable. 

Any thoughts on this? e.g. shifting the hint to top left of the button/add transparency to the hint...etc

Thank you!

**Comment by FANYD** [comment]
-

**Comment by FANYD** [comment]
+1

**Comment by dexterleng** [comment]
My reasoning for positioning in the center are:

1. The clicking mechanism for Vimac is to move the mouse to the center of the element and click there. Vimium can simply call the click method of an HTML button. Since this is what is being done, I believe it is much more "correct" to position the hint in the center of a button.

There is a equivalent "click method" in the macOS accessibility API (`AXPress`), but not all elements/buttons Vimac show hints for has that action (Currently hints are shown for element with actions.count > 0).

2. Vimac currently shows a bunch of hints, especially for web content. By positioning the hints at the top left, it can be really hard where the actual mouse click will occur.

**Comment by dexterleng** [comment]
Until there is a move to relying on AXPress as the clicking mechanism, I will continue to position the hints in the center. I'll open a ticket for transparency configuration.

**Comment by Stooovie** [comment]
A transparency setting would fix this and be really useful.
