### ISSUE TITLE
vimac not showing suggestions for Firefox

### ISSUE THREAD

**Issue by Vijay-Duke** [dexterleng/vimac#200]
I am not sure if its a bug. I do not get any suggestions for links/buttons/extensions when I invoke vimac on firefox. Sometimes it does show the hints.

**Comment by phlind** [comment]
You mean for links on the website? I'm not using Firefox, but Brave. I get hints for the UI elements like tabs, the favorites bar and add-on icons and only one hint for the website content. I think this behavior might be intended, because there are separate plugins for browser navigation like Vimium. I use both together and it works quite well for me to separate things.

But if you mean the UI elements, there might be a bug related to firefox.

**Comment by leighmcculloch** [comment]
Vimac works for Safari, and supports selecting all elements even links inside the web page. In Firefox though the only options are to click on the middle of the web page, or to close, minimize or expand the window. It appears like Vimac can't get information about what interactive elements are available on screen, maybe via accessibility APIs?

**Comment by Vijay-Duke** [comment]
> Vimac works for Safari, and supports selecting all elements even links inside the web page. In Firefox though the only options are to click on the middle of the web page, or to close, minimize or expand the window. It appears like Vimac can't get information about what interactive elements are available on screen, maybe via accessibility APIs?

**Comment by galtenberg** [comment]
This issue is definitely unresolved, even though closed. Firefox simply has no on-page hints.

**Comment by dexterleng** [comment]
Firefox is disabled in Vimac for the same reason Chromium is. Refer to #78.

**Comment by galtenberg** [comment]
🍺
