### ISSUE TITLE
Some hints disappeared in new version

### ISSUE THREAD

**Issue by FANYD** [dexterleng/vimac#202]
![image](https://user-images.githubusercontent.com/22900911/91694525-3e8d5a80-eb9f-11ea-8ed7-94fac8a7496e.png)

**Comment by dexterleng** [comment]
@FANYD Must be because those elements have no "actions". Do you have Xcode installed? It comes with Accessibility Inspector, which you can use to check for the element information. My guess is that 3.10 has hints shown for those profile pictures because they are actionless `AXRows`, which was an edge case that hints were shown for in 0.3.10 but had removed since. Could you confirm this?

**Comment by FANYD** [comment]
> @FANYD Must be because those elements have no "actions". Do you have Xcode installed? It comes with Accessibility Inspector, which you can use to check for the element information. My guess is that 3.10 has hints shown for those profile pictures because they are actionless `AXRows`, which was an edge case that hints were shown for in 0.3.10 but had removed since. Could you confirm this?

![image](https://user-images.githubusercontent.com/22900911/91788681-6502d280-ec3f-11ea-88c0-93e73c49fbee.png)
