### ISSUE TITLE
GitHub's Code button isn't clickable

### ISSUE THREAD

**Issue by zhigang1992** [dexterleng/vimac#292]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1057756/105619731-8784ca80-5e30-11eb-9ebe-d9c564d4e072.png">

Latest master, it's a bit strange because it was working before. I've used that a couple of times.

**Comment by dexterleng** [comment]
Ah :/ I knew this would happen.

I removed `AXStaticTextSearchKey` from search keys. The `Code` button ideally should be shown because I'm querying for `AXButtonSearchKey`, but I guess the button isn't accessibility friendly. Previously a hint would still should for the underlying static text `"Code"`.

**Comment by dexterleng** [comment]
If you look at devtools the button is actually a `<summary>`

<img width="795" alt="Screenshot 2021-01-24 at 12 35 09 AM" src="https://user-images.githubusercontent.com/34204380/105607956-04d22000-5ddc-11eb-86c4-925b9e75661e.png">


I'll have to think through whether to support static text as a workaround.

**Comment by zhigang1992** [comment]
Ah, in that case I think we should let GitHub fix it. 😄
