### ISSUE TITLE
Enabling experimental non-native support interferes with up/down arrow keys in Safari

### ISSUE THREAD

**Issue by sooheon** [dexterleng/vimac#351]
Maybe happens for other apps, but noticed in Safari. Enable non-native support, and now you can't scroll regularly with up/down arrows in webpages in Safari.

**Comment by blackketter** [comment]
I was wondering what happened.  Confirmed for me too.

**Comment by dexterleng** [comment]
I don't think there is anything I can do about that.  I doubt Apple will fix it on their end.

I cannot enable AXEnhancedUserInterface immediately after activation, because the API doesn't wait for the AX plumbing to be set up. Hence, I choose to keep it enabled at all times.

If Vimac is somehow the default always-on "mode", and users have to exit Vimac to interact with the GUI normally, then I think I could keep this attribute on at all times, except when the user wants to exit Vimac. I have proposed a always-on "workflow mode" idea here https://github.com/dexterleng/vimac/issues/331#issuecomment-792540446 that would make this possible.

**Comment by sooheon** [comment]
API limitations are what they are, but at least it should be documented in the option toggle. Being "always on" and entering "insert mode" with `i` is one approach that Vimium takes.
