### ISSUE TITLE
vimac crashes when Transmit is the frontmost application

### ISSUE THREAD

**Issue by jimmyhartington** [dexterleng/vimac#353]
If I activate vimac with Transmit from Panic as the frontmost application, then vimac crashes.

**Comment by dexterleng** [comment]
I can replicate this.

The issue seems to lie with this component:

![Screenshot 2021-03-22 at 4 45 08 PM](https://user-images.githubusercontent.com/34204380/111962982-fa0edf80-8b2d-11eb-8f78-9268bdfb6f95.png)

One of its children is... itself?

<img width="524" alt="Screenshot 2021-03-22 at 4 45 29 PM" src="https://user-images.githubusercontent.com/34204380/111963019-05620b00-8b2e-11eb-80a8-77864c141ff8.png">

**Comment by dexterleng** [comment]
From my understanding accessibility trees shouldn't be cyclic (they would be a graph otherwise). I would suggest contacting them about this issue

Should be fixable on my end - keep track of fetched elements in a set, and refer to it before traversing a child element.

**Comment by jimmyhartington** [comment]
I have contacted Panic support. And they are looking into it.
