### ISSUE TITLE
FR: single-letter hints for focused window

### ISSUE THREAD

**Issue by ultraGentle** [dexterleng/vimac#427]
Most of my desired actions take place within the currently focused window, 
so it would be nice if the hints for the focused window were the shortest and least-obscuring
 -- i.e., single letter.

**Comment by dexterleng** [comment]
This has been discussed before and its something I would like to see in Vimac #293

**Comment by ultraGentle** [comment]
@dexterleng I think my description was unclear, sorry -- this is not a dupe of #293.  

I'm not suggesting hints to allow switching windows. 

Rather, I am suggesting that, **within the currently focused window, there is a priority for single-letter hints.**  

The rationale is that the currently-focused window is most often what you want to interact with, and single letter hints there will have the biggest impact on speed with the least obfuscation.  

(PS: If I'm wrong, and this is a dupe, double sorry!)

**Comment by GanZhiXiong** [comment]
@dexterleng 
I think the prompt letter algorithm should be changed to give the current app priority to a single letter, because most of the time an app doesn't have too many clickable controls, and if there are more than 26 clickable controls, the extra controls will use two prompt letters.

This will greatly contribute to keystroke efficiency.

**Comment by GanZhiXiong** [comment]
@dexterleng 
Vimium supports a single letter, and you can copy its algorithm.

![image](https://user-images.githubusercontent.com/27394631/140368385-c69ed4cf-abd4-42b0-bd51-632c4b5dd372.png)
