### ISSUE TITLE
Start Vimac when macOS boots up

### ISSUE THREAD

**Issue by dexterleng** [dexterleng/vimac#88]

**Comment by ogirginc** [comment]
Is this different than the "Launch on Startup" feature or just not closed this issue yet?

**Comment by dexterleng** [comment]
Forgot to close it, although I've received feedback saying it's broken.

**Comment by ogirginc** [comment]
Can confirm this! :)

**Comment by mmroczka** [comment]
still seems broken to me. Or at least it doesn't reliably start up.

**Comment by rbugajewski** [comment]
I also observe the same issue. If the option “Launch at login” is set, Vimac doesn’t work right after launch. If I exit and manually launch the application again, it works without issues. I don’t know enough about this repository’s source code, but from a naïve perspective this looks like some sort of race condition. Maybe some preconditions aren’t met, because the operating system is still in its initialization phase? Maybe the launch can be postponed, which wouldn’t be elegant, but at least it would work after some timeout?

The same behavior can be observed if the option is unchecked, but “Reopen windows when logging back in” is checked.

I’ve seen that #259 could be a duplicate of this issue, but it doesn’t have enough information. I also use ⌃Space and the described behavior is the same. Maybe that one can be closed as a duplicate.

Thanks so much for your work! I use this application daily and it greatly enhances my workflow.

**Comment by dexterleng** [comment]
Vimac 0.3.11 (released 29 Aug) is signed, which for me addressed the inconsistent launch issue.


@rbugajewski If you are on 0.3.11 or later, could you check that there are no extra binaries lying around (e.g. in your Downloads)?

**Comment by rbugajewski** [comment]
@dexterleng Thanks for addressing this issue. I updated to 0.3.13 and there are definitely big improvements, but the issue isn’t fully fixed. Previously I didn’t really know how to reproduce the issue, but the shortcut almost never worked right after launch. I switched with Command-Tab to another app, then to another one, switched back, sometimes I closed an app, then switched back, and then somehow surprisingly Vimac started to work, sometimes I had to restart Vimac in between. Once I went through this mumbo jumbo Vimac consistently worked. All of this is gone now!

There is only one issue remaining on my machine, and thankfully I can now consistently reproduce it:

1. Launch Vimac, make sure that two applications are open and the respective windows in front (I used Vivaldi browser & Finder). In my test case Finder is in front when Vimac launches.
2. Use keyboard shortcut, observe how nothing happens.
3. Command-Tab to the other application (Vivaldi in my case), then cycle back to the Finder.
4. Use keyboard shortcut, and let the Vimac magic happen!

So it looks like the issue was indeed fixed, and there’s one remaining thing: when an application is active and Vimac launches, it somehow needs to pick it up (maybe this can be done via a fast workaround, e. g. make the front-most application inactive, then active again after a fixed amount of ms directly after Vimac launch, the user wouldn’t probably realize this).

This isn’t anymore a high priority issue I think, because the behavior can be always fixed with a fast Command-Tab.

**Comment by dexterleng** [comment]
@rbugajewski Ah - I am aware of this issue - Vimac keep track of the front most window by listening for "window focus" events. So when you launch the application, until that event has been fired (e.g. after a CMD-Tab) Vimac won't work.

**Comment by dexterleng** [comment]
Seems like something that could confuse users. I'll open an issue! Closing this now.
